export const GET_GREETING_COMPLETED = 'GET_GREETING_COMPLETED';
export const GET_APOD_COMPLETED = 'GET_APOD_COMPLETED';
export const GET_OC_REGISTRY_BASE_URL = 'GET_OC_REGISTRY_BASE_URL';
export const RENDER_UNLOADED_COMPONENTS = 'RENDER_UNLOADED_COMPONENTS';
export const SET_COUNTER = 'SET_COUNTER';
